apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: bW9uZ29hZG1pbg==  # Base64 encoded value of "mongoadmin"
  password: c2VjdXJlcGFzc3dvcmQ=  # Base64 encoded value of "securepassword"
