apiVersion: v1

data:

  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJteS1kb2NrZXItdXNlcm5hbWUiLCJwYXNzd29yZCI6Im15LWRvY2tlci1wYXNzd29yZCIsImVtYWlsIjoibXktZW1haWxAZXhhbXBsZS5jb20iLCJhdXRoIjoiYlhrdFpHOWphMlZ5TFhWelpYSnVZVzFsT20xNUxXUnZZMnRsY2kxd1lYTnpkMjl5WkE9PSJ9fX0=

kind: Secret

metadata:

  creationTimestamp: null

  name: dockerhub-secret

type: kubernetes.io/dockerconfigjson
