apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-join-token
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/control-plane:
          tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            effect: "NoSchedule"
          restartPolicy: OnFailure
          containers:
          - name: token-generator
            image: amazonlinux
            command: ["/bin/sh", "-c"]
            args:
              - |
                command=$(kubeadm token create --print-join-command)
                aws secretsmanager update-secret --secret-id tal-k8s-join-token --secret-string "$command" --region eu-north-1
          serviceAccountName: token-updater-sa