apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polybot-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/TalSilbiger2/INTPolybotServiceKubernetes.git'
    targetRevision: main
    path: infra/polybotInfra
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
