apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polybot-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/TalSilbiger2/INTPolybotServiceKubernetes/infra.git'
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true