apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
        - name: polybot
          image: docker.io/talsilbiger/polybotk:latest  # ✅ This will be updated automatically
          ports:
            - containerPort: 8443
          env:
            - name: TELEGRAM_APP_URL
              value: "https://tal-polybot-route53.devops-int-college.com"
            - name: S3_BUCKET_NAME
              value: "tal-polybot-docker-bucket"
            - name: SQS_QUEUE_URL
              value: "https://sqs.eu-north-1.amazonaws.com/352708296901/tal-polybot-queue"
#            - name: MONGO_USER
#              valueFrom:
#                secretKeyRef:
#                  name: mongo-secret
#                  key: username
#            - name: MONGO_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mongo-secret
#                  key: password
            # - name: MONGODB_URI
            #  value: mongodb://mongo:27017
#      imagePullSecrets:
#        - name: dockerhub-secret
